---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd-crds
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: 1.8.0
  interval: 5m0s
  releaseName: linkerd-crds
