---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger
spec:
  releaseName: flagger
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chartRef:
    kind: OCIRepository
    name: flagger
    namespace: flux-system
  interval: 5m0s
  values:
    meshProvider: gatewayapi:v1 #linkerd
    linkerdAuthPolicy:
      create: true
    metricsServer: http://prometheus.linkerd-viz:9090
