apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backend
  namespace: default
spec:
  provider: kubernetes
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  progressDeadlineSeconds: 60
  service:
    port: 8800
    targetPort: 8800
    name: backend
    portDiscovery: true

  skipAnalysis: false
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    threshold: 2
    stepWeights: [1, 5, 20, 80]
    stepWeightPromotion: 100

    metrics:
      - name: request-success-rate
        interval: 15s
        thresholdRange:
          min: 99
      - name: request-duration
        interval: 15s
        thresholdRange:
          max: 100
