apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  service:
    port: 8800
  skipAnalysis: false
  analysis:
    interval: 60s
    threshold: 1
    stepWeights: [1, 5, 20, 80]
    stepWeightPromotion: 100
    metrics:
      - name: request-success-rate
        interval: 20s
        thresholdRange:
          min: 99
      - name: request-duration
        interval: 20s
        thresholdRange:
          max: 100
