---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name:  app
        image: ghcr.io/kirillsalykin/dummy-backend
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8800
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        livenessProbe:
          httpGet:
            path: /livez
            port: http
        resources:
          requests:
            cpu:    100m
            memory: 40Mi
          limits:
            memory: 80Mi
