apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - canary.yaml
images:
  - name: ghcr.io/kirillsalykin/dummy-backend
    newName: ghcr.io/kirillsalykin/dummy-backend
    newTag: "1741346069" # {"$imagepolicy": "flux-system:backend:tag"}
