apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: k6
spec:
  interval: 5m0s
  chart:
    spec:
      chart: k6-operator
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
     installCRDs: true
