apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 5m0s
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.16.11
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
