apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - crds.yaml
  - certs.yaml
  - control-plane-release.yaml
secretGenerator:
  - name: linkerd-trust-anchor
    namespace: linkerd
    type: kubernetes.io/tls
    files:
      - tls.crt=ca.crt
      - tls.key=ca.key
