---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: ghcr.io/kirillsalykin/dummy-backend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend
  filterTags:
    pattern: '^\d+$'
  policy:
    numerical:
      order: asc
